#include "Mt32Translator.h"

#include <algorithm>
#include <cstdio>
#include <cstring>

namespace {

// Addresses are the three 7-bit SysEx address bytes packed together, as Synth::readMemory() takes them.
constexpr uint32_t pack(uint32_t high, uint32_t mid, uint32_t low) {
    return (high << 14) | (mid << 7) | low;
}

// The MT-32's memory areas, which the D-110 shares.
constexpr uint32_t kPatchTemp = pack(0x03, 0x00, 0x00);    // 16 bytes for each of parts 1-8 and rhythm
constexpr uint32_t kRhythmSetup = pack(0x03, 0x01, 0x10);  // 4 bytes for each of keys 24-108
constexpr uint32_t kRhythmSetupEnd = kRhythmSetup + 85 * 4;
constexpr uint32_t kToneTemp = pack(0x04, 0x00, 0x00);     // Parts 1-8, one tone (246 bytes) each
constexpr uint32_t kToneSize = 246;
constexpr uint32_t kToneTempEnd = kToneTemp + 8 * kToneSize;
constexpr uint32_t kPatchMemory = pack(0x05, 0x00, 0x00);  // 128 x 8 bytes (the D-110's timbre memory)
constexpr uint32_t kPatchMemoryEnd = kPatchMemory + 128 * 8;
constexpr uint32_t kToneMemory = pack(0x08, 0x00, 0x00);   // 64 tones in 256-byte slots
constexpr uint32_t kToneMemoryEnd = kToneMemory + 64 * 256;
constexpr uint32_t kSystem = pack(0x10, 0x00, 0x00);
constexpr uint32_t kSystemSize = 0x17;                    // The D-110's goes on to 20H
constexpr uint32_t kDisplay = pack(0x20, 0x00, 0x00);
constexpr uint32_t kWriteRequest = pack(0x40, 0x00, 0x00);  // Tone write: 2 bytes per part (slot, 0 = internal)
constexpr uint32_t kReset = pack(0x7F, 0x00, 0x00);

// Tone layout: common parameters, then 4 partials.
constexpr uint32_t kToneCommonSize = 14;
constexpr uint32_t kPartialSize = 58;
constexpr uint32_t kStructure12 = 10, kStructure34 = 11;
constexpr uint32_t kPitchCoarse = 0, kPitchFine = 1, kWaveform = 4, kPcmWave = 5;

// Patch temp / patch memory offsets.
constexpr uint32_t kGroup = 0, kNumber = 1, kKeyShift = 2, kReverbSwitch = 6, kDummy = 7, kPanpot = 9, kKeyRangeLower = 10, kKeyRangeUpper = 11;
// System area offsets.
constexpr uint32_t kSystemReverbMode = 0x01, kSystemReserves = 0x04, kSystemChannels = 0x0D, kSystemMasterVolume = 0x16;

// Whether partials 1 and 2 (or 3 and 4) of each structure play PCM: bit 1 the first, bit 0 the second (as mt32emu).
constexpr uint8_t kPartialStruct[13] = {0, 0, 2, 2, 1, 3, 3, 0, 3, 0, 2, 1, 3};

// MT-32 reverb modes Room, Hall, Plate, Tap delay -> D-110 Small Room, Medium Hall, Plate, Delay 1.
constexpr uint8_t kReverbModes[4] = {0, 2, 4, 5};

// MT-32 waves -> D-110 waves, generated by tools/mt32_waves.py (see there for the method). The MT-32 wave names follow
// common MT-32 editor lists, corrected where the MT-32's PCM table shows a loop's sample; the D-110's are from its
// manual (PCM sound list). Pitch corrections keep the MT-32's pitch:
//  - 16 MT-32 samples are in the D-110's PCM ROM too (Organ, Violin, Tubular Bells, Pan Pipes ...), and their
//    corrections are exact: the difference of the two control ROMs' pitch words.
//  - Other melodic waves: the MT-32 tunes them to C4 at key 60 and coarse C4; the D-110 tunes each to a C from C2 to
//    C6 (measured).
//  - The D-110's bank-2 "Loop" waves repeat a bank-1 sample at its recorded rate, as the MT-32's loops repeat theirs
//    at the sample's pitch.
//  - Drums and effects keep their rate. Orchestra Hit has no D-series sample and becomes Violin-2's attack.
const Mt32Translator::WaveMapping kWaves[256] = {
    {  0,   0,   0,   0},  //   0 Ac. Bass Drum          -> b1-001 Bass Drum-1
    {  3,   0,   0,   3},  //   1 Ac. Snare Drum         -> b1-004 Snare Drum-1
    {  3,   4,   0,   3},  //   2 El. Snare Drum         -> b1-004 Snare Drum-1
    {  8,   0,   0,   8},  //   3 Electric Tom           -> b1-009 Tom Tom-2
    {  9,   0,   0,   9},  //   4 Closed Hihat           -> b1-010 High-Hat
    { 10,   0,   0,  10},  //   5 Open Hihat             -> b1-011 High-Hat (Loop)
    { 11,   0,   0,  11},  //   6 Crash Cymbal           -> b1-012 Crash Cymbal-1
    { 12,   0,   0,  12},  //   7 Crash Cymbal (loop)    -> b1-013 Crash Cymbal-2 (Loop)
    { 13,   0,   0,  13},  //   8 Ride cymbal            -> b1-014 Ride Cymbal-1
    { 18,   0,   0,  18},  //   9 Rim Shot               -> b1-019 Rim Shot
    { 19,   0,   0,  19},  //  10 Hand Clap              -> b1-020 Hand Clap
    { 20,   0,   0,  20},  //  11 Muted Conga            -> b1-021 Mute High Conga
    { 21,   0,   0,  21},  //  12 Conga                  -> b1-022 Conga
    { 22,   0,   0,  22},  //  13 Bongo                  -> b1-023 Bongo
    { 23,   0,   0,  23},  //  14 Cowbell                -> b1-024 Cowbell
    { 24,   0,   0,  24},  //  15 Tambourine             -> b1-025 Tambourine
    { 25,   0,   0,  25},  //  16 Agogo Bell             -> b1-026 Agogo
    { 26,   0,   0,  26},  //  17 Claves                 -> b1-027 Claves
    { 27,   0,   0,  27},  //  18 Timbale                -> b1-028 Timbale High
    { 29,   0,   0,  29},  //  19 Cabasa                 -> b1-030 Cabasa
    { 34, -12,   0,  34},  //  20 Keypress               -> b1-035 Piano Forte Thump
    { 35,  12, -16,  35},  //  21 Perc Organ             -> b1-036 Organ Percussion
    { 38, -12,   0,  38},  //  22 Trombone               -> b1-039 Trombone
    { 36, -12,   0,  36},  //  23 Trumpet                -> b1-037 Trumpet
    {110,   0,   0, 110},  //  24 Breath Noise (loop)    -> b1-111 Noise (Loop)
    { 39, -12,   0,  39},  //  25 Clarinet               -> b1-040 Clarinet
    { 41, -12,   0,  41},  //  26 Flute                  -> b1-042 Flute Low
    { 42, -12,  -8,  42},  //  27 Pan Pipes              -> b1-043 Steamer
    { 44,   0,  43,  44},  //  28 Shakuhachi             -> b1-045 Breath
    { 79,   0,   0,  79},  //  29 Alto Sax               -> b1-080 Sax-2 (Loop)
    { 78,  12,   0,  78},  //  30 Baritone Sax           -> b1-079 Sax-1 (Loop)
    { 47,  12,   0,  47},  //  31 Marimba                -> b1-048 Marimba
    { 46,   0,   0,  46},  //  32 Vibraphone             -> b1-047 Vibraphone Low
    { 49, -12,   0,  49},  //  33 Xylophone              -> b1-050 Xylophone Low
    { 51, -36, -34,  51},  //  34 Tubular Bells          -> b1-052 Wind Bell
    { 62,  12,   0,  62},  //  35 Fingered Bass          -> b1-063 Electric Bass
    { 60,  12,   0,  60},  //  36 Slap Bass              -> b1-061 Thump Bass
    { 92,  24,   0,  92},  //  37 Picked Bass (loop)     -> b1-093 Electric Piano-2 (Loop)
    { 61,  12,  -2,  61},  //  38 Acoustic Bass          -> b1-062 Acoustic Bass
    { 63,   0,   0,  63},  //  39 Nylon Guitar           -> b1-064 Gut Guitar
    { 33,  12,   0,  33},  //  40 Steel Guitar           -> b1-034 Acoustic Piano Low
    { 66, -12,   0,  66},  //  41 Pizzicato              -> b1-067 Pizzicato
    { 67, -24,   0,  67},  //  42 Harp                   -> b1-068 Harp
    { 94,  12,   8,  94},  //  43 Harpsichord (loop)     -> b1-095 Harpsichord-2 (Loop)
    { 68,  12,   0,  68},  //  44 Bow string             -> b1-069 Contrabass
    { 70, -13,   7,  70},  //  45 Violin                 -> b1-071 Violin-1
    { 30,  12,   0,  30},  //  46 Timpani                -> b1-031 Timpani Attack
    { 71,   0,   0,  71},  //  47 Orchestra Hit          -> b1-072 Violin-2
    { 43, -12, -12,  43},  //  48 Flute 2                -> b1-044 Indian Flute
    { 73,   0,  12,  73},  //  49 Organ (loop)           -> b1-074 Drawbars (Loop)
    {101, -22,  14, 101},  //  50 Bowed Glass (loop)     -> b1-102 Spectrum-2 (Loop)
    { 95, -14, -30,  95},  //  51 Telephone              -> b1-096 Telephone Bell (Loop)
    {105, -27,  -3, 105},  //  52 Bowed Glass            -> b1-106 Spectrum-6 (Loop)
    {106, -18,   0, 106},  //  53 Spectrum 7 (loop)      -> b1-107 Spectrum-7 (Loop)
    {128,   0,   0,   0},  //  54 Ac. Bass Drum #        -> b2-001 Bass Drum-1* (bank 1: Bass Drum-1)
    {131,   0,   0,   3},  //  55 Ac. Snare Drum #       -> b2-004 Snare Drum-1* (bank 1: Snare Drum-1)
    {131,   4,   0,   3},  //  56 El. Snare Drum #       -> b2-004 Snare Drum-1* (bank 1: Snare Drum-1)
    {136,   0,   0,   8},  //  57 Ac. Tom #              -> b2-009 Tom Tom-2* (bank 1: Tom Tom-2)
    {137,   0,   0,   9},  //  58 Closed Hihat #         -> b2-010 High-Hat* (bank 1: High-Hat)
    {138,   0,   0,  10},  //  59 Open Hihat (loop) #    -> b2-011 High-Hat (Loop)* (bank 1: High-Hat (Loop))
    {139,   0,   0,  11},  //  60 Crash Cymbal #         -> b2-012 Crash Cymbal-1* (bank 1: Crash Cymbal-1)
    {140,   0,   0,  12},  //  61 Crash Cymbal (loop) #  -> b2-013 Crash Cymbal-2 (Loop)* (bank 1: Crash Cymbal-2 (Loop))
    {141,   0,   0,  13},  //  62 Ride cymbal #          -> b2-014 Ride Cymbal-1* (bank 1: Ride Cymbal-1)
    {146,   0,   0,  18},  //  63 Rim shot #             -> b2-019 Rim Shot* (bank 1: Rim Shot)
    {147,   0,   0,  19},  //  64 Hand clap #            -> b2-020 Hand Clap* (bank 1: Hand Clap)
    {148,   0,   0,  20},  //  65 Mute Conga #           -> b2-021 Mute High Conga* (bank 1: Mute High Conga)
    {149,   0,   0,  21},  //  66 Conga #                -> b2-022 Conga* (bank 1: Conga)
    {150,   0,   0,  22},  //  67 Bongo #                -> b2-023 Bongo* (bank 1: Bongo)
    {151,   0,   0,  23},  //  68 Cowbell #              -> b2-024 Cowbell* (bank 1: Cowbell)
    {152,   0,   0,  24},  //  69 Tambourine #           -> b2-025 Tambourine* (bank 1: Tambourine)
    {153,   0,   0,  25},  //  70 Agogo #                -> b2-026 Agogo* (bank 1: Agogo)
    {154,   0,   0,  26},  //  71 Claves #               -> b2-027 Claves* (bank 1: Claves)
    {155,   0,   0,  27},  //  72 Timbale #              -> b2-028 Timbale High* (bank 1: Timbale High)
    {157,   0,   0,  29},  //  73 Cabasa #               -> b2-030 Cabasa* (bank 1: Cabasa)
    {158,   0,   0,   0},  //  74 Bass Drum (loop)       -> b2-031 Loop-1 (bank 1: Bass Drum-1)
    {160,   0,   0,   3},  //  75 Snare (loop)           -> b2-033 Loop-3 (bank 1: Snare Drum-1)
    {160,   4,   0,   3},  //  76 El. Snare (loop)       -> b2-033 Loop-3 (bank 1: Snare Drum-1)
    {163,   0,   0,   8},  //  77 Electric Tom (loop)    -> b2-036 Loop-6 (bank 1: Tom Tom-2)
    {164,   0,   0,  10},  //  78 Hihat (loop)           -> b2-037 Loop-7 (bank 1: High-Hat (Loop))
    {165,   0,   0,  12},  //  79 Crash Cymbal (loop)    -> b2-038 Loop-8 (bank 1: Crash Cymbal-2 (Loop))
    {166,   0,   0,  14},  //  80 Ride cymbal (loop)     -> b2-039 Loop-9 (bank 1: Ride Cymbal-2 (Loop))
    { 14,   0,   0,  14},  //  81 Ride cymbal 2 (loop)   -> b1-015 Ride Cymbal-2 (Loop)
    {170,   0,   0,  18},  //  82 Rim (loop)             -> b2-043 Loop-13 (bank 1: Rim Shot)
    {171,   0,   0,  19},  //  83 Hand clap (loop)       -> b2-044 Loop-14 (bank 1: Hand Clap)
    {173,   0,   0,  20},  //  84 Muted Conga (loop)     -> b2-046 Loop-16 (bank 1: Mute High Conga)
    {174,   0,   0,  21},  //  85 Conga (loop)           -> b2-047 Loop-17 (bank 1: Conga)
    {175,   0,   0,  22},  //  86 Bongo (loop)           -> b2-048 Loop-18 (bank 1: Bongo)
    {176,   0,   0,  23},  //  87 Cowbell (loop)         -> b2-049 Loop-19 (bank 1: Cowbell)
    {177,   0,   0,  24},  //  88 Tambourine (loop)      -> b2-050 Loop-20 (bank 1: Tambourine)
    {179,   0,   0,  25},  //  89 Agogo (loop)           -> b2-052 Loop-22 (bank 1: Agogo)
    {180,   0,   0,  26},  //  90 Claves (loop)          -> b2-053 Loop-23 (bank 1: Claves)
    {181,   0,   0,  27},  //  91 Timbale (loop)         -> b2-054 Loop-24 (bank 1: Timbale High)
    {183,   0,   0,  29},  //  92 Cabasa (loop)          -> b2-056 Loop-26 (bank 1: Cabasa)
    {186, -24,   0,  34},  //  93 Keypress (loop)        -> b2-059 Loop-29 (bank 1: Piano Forte Thump)
    {187,   1, -19,  35},  //  94 Perc Organ (loop)      -> b2-060 Loop-30 (bank 1: Organ Percussion)
    {190, -23, -14,  38},  //  95 Trombone (loop)        -> b2-063 Loop-33 (bank 1: Trombone)
    {188, -20,  -6,  36},  //  96 Trumpet (loop)         -> b2-061 Loop-31 (bank 1: Trumpet)
    {193, -11, -14,  39},  //  97 Clarinet (loop)        -> b2-066 Loop-36 (bank 1: Clarinet)
    {194, -20, -41,  40},  //  98 Flute (loop)           -> b2-067 Loop-37 (bank 1: Flute High)
    {195, -11, -49,  42},  //  99 Pan Pipes (loop)       -> b2-068 Loop-38 (bank 1: Steamer)
    {192,  -5,   0,  44},  // 100 Shakuhachi (loop)      -> b2-065 Loop-35 (bank 1: Breath)
    { 79,   0,   0,  79},  // 101 Alto Sax (loop)        -> b1-080 Sax-2 (Loop)
    { 78,  12,   0,  78},  // 102 Baritone Sax (loop)    -> b1-079 Sax-1 (Loop)
    {198,  13, -43,  47},  // 103 Marimba (loop)         -> b2-071 Loop-41 (bank 1: Marimba)
    {197,   3, -18,  46},  // 104 Vibraphone (loop)      -> b2-070 Loop-40 (bank 1: Vibraphone Low)
    {199, -34, -12,  48},  // 105 Xylophone (loop)       -> b2-072 Loop-42 (bank 1: Xylophone High)
    {200, -58,  47,  51},  // 106 Tubular Bells (loop)   -> b2-073 Loop-43 (bank 1: Wind Bell)
    { 83,  12,   0,  83},  // 107 Fingered Bass (loop)   -> b1-084 Electric Bass-1 (Loop)
    { 81,  12,   0,  81},  // 108 Slap Bass (loop)       -> b1-082 Slap Bass (Loop)
    {209,  11, -18,  61},  // 109 Acoustic Bass (loop)   -> b2-082 Loop-52 (bank 1: Acoustic Bass)
    {213,  -2, -12,  63},  // 110 Nylon Guitar (loop)    -> b2-086 Loop-56 (bank 1: Gut Guitar)
    {214,  -2,  -2,  64},  // 111 Steel Guitar (loop)    -> b2-087 Loop-57 (bank 1: Steel Guitar)
    {216, -14,   6,  66},  // 112 Pizzicato (loop)       -> b2-089 Loop-59 (bank 1: Pizzicato)
    {217, -23, -15,  67},  // 113 Harp (loop)            -> b2-090 Loop-60 (bank 1: Harp)
    {218,  13, -25,  68},  // 114 Bow string (loop)      -> b2-091 Loop-61 (bank 1: Contrabass)
    {220, -13,  44,  70},  // 115 Violin (loop)          -> b2-093 Loop-63 (bank 1: Violin-1)
    {185,  12,   0,  30},  // 116 Timpani (loop)         -> b2-058 Loop-28 (bank 1: Timpani Attack)
    { 90,   0,   0,  90},  // 117 Orchestra Hit (loop)   -> b1-091 Violin (Loop)
    {191, -23, -41,  43},  // 118 Flute 2 (loop)         -> b2-064 Loop-34 (bank 1: Indian Flute)
    {229,   0,   0, 110},  // 119 Perc. loop 1           -> b2-102 Jam-8 (Loop) (bank 1: Noise (Loop))
    {222,   0,   0, 110},  // 120 Perc. loop 2           -> b2-095 Jam-1 (Loop) (bank 1: Noise (Loop))
    {227,   0,   0, 110},  // 121 Orch&Perc loop         -> b2-100 Jam-6 (Loop) (bank 1: Noise (Loop))
    {223,   0,   0, 110},  // 122 Wind&Perc loop         -> b2-096 Jam-2 (Loop) (bank 1: Noise (Loop))
    {239,   0,   0, 110},  // 123 Guitar & Bass loop     -> b2-112 Jam-18 (Loop) (bank 1: Noise (Loop))
    {234,   0,   0, 110},  // 124 Orchestra loop         -> b2-107 Jam-13 (Loop) (bank 1: Noise (Loop))
    {228,   0,   0, 110},  // 125 Perc. loop 3           -> b2-101 Jam-7 (Loop) (bank 1: Noise (Loop))
    {224,   0,   0, 110},  // 126 Bass & Perc. loop      -> b2-097 Jam-3 (Loop) (bank 1: Noise (Loop))
    {242,   0,   0, 110},  // 127 Bass & Snare loop      -> b2-115 Jam-21 (Loop) (bank 1: Noise (Loop))
    {110,   0,   0, 110},  // 128 Laugh #                -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 129 Applause #             -> b1-111 Noise (Loop)
    { 51,   0,   0,  51},  // 130 Windchime #            -> b1-052 Wind Bell
    { 11,   0,   0,  11},  // 131 Crash #                -> b1-012 Crash Cymbal-1
    {110,   0,   0, 110},  // 132 Train #                -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 133 Wind #                 -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 134 Bird #                 -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 135 Stream #               -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 136 Door Creak #           -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 137 Scream #               -> b1-111 Noise (Loop)
    {  0,   0,   0,   0},  // 138 Punch #                -> b1-001 Bass Drum-1
    {  7,   0,   0,   7},  // 139 Footsteps #            -> b1-008 Tom Tom-1
    {  3,   0,   0,   3},  // 140 Door Slam #            -> b1-004 Snare Drum-1
    {110,   0,   0, 110},  // 141 Car Start #            -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 142 Aircraft #             -> b1-111 Noise (Loop)
    {  5,   0,   0,   5},  // 143 Gun Shot #             -> b1-006 Snare Drum-3
    {110,   0,   0, 110},  // 144 Horse #                -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 145 Thunder #              -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 146 Bubble #               -> b1-111 Noise (Loop)
    {  1,   0,   0,   1},  // 147 Heartbeat #            -> b1-002 Bass Drum-2
    {110,   0,   0, 110},  // 148 Engine #               -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 149 Tyre Screech #         -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 150 Siren #                -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 151 Helicopter #           -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 152 Dog Bark #             -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 153 Car Pass #             -> b1-111 Noise (Loop)
    { 98,   0,   0,  98},  // 154 Male Voice #           -> b1-099 Male Voice-1 (Loop)
    {110,   0,   0, 110},  // 155 Machine Gun #          -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 156 Starship #             -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 157 Laugh (Loop) #         -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 158 Applause (Loop) #      -> b1-111 Noise (Loop)
    {200,   0,   0, 110},  // 159 Windchime (Loop) #     -> b2-073 Loop-43 (bank 1: Noise (Loop))
    { 12,   0,   0,  12},  // 160 Crash (Loop) #         -> b1-013 Crash Cymbal-2 (Loop)
    {110,   0,   0, 110},  // 161 Train (Loop) #         -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 162 Wind (Loop) #          -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 163 Bird (Loop) #          -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 164 Stream (Loop) #        -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 165 Door Creak (Loop) #    -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 166 Scream (Loop) #        -> b1-111 Noise (Loop)
    {158,   0,   0, 110},  // 167 Punch (Loop) #         -> b2-031 Loop-1 (bank 1: Noise (Loop))
    {163,   0,   0, 110},  // 168 Footsteps (Loop) #     -> b2-036 Loop-6 (bank 1: Noise (Loop))
    {110,   0,   0, 110},  // 169 Door Slam (Loop) #     -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 170 Car Start (Loop) #     -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 171 Aircraft (Loop) #      -> b1-111 Noise (Loop)
    {162,   0,   0, 110},  // 172 Gun Shot (Loop) #      -> b2-035 Loop-5 (bank 1: Noise (Loop))
    {110,   0,   0, 110},  // 173 Horse (Loop) #         -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 174 Thunder (Loop) #       -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 175 Bubble (Loop) #        -> b1-111 Noise (Loop)
    {159,   0,   0, 110},  // 176 Heartbeat (Loop) #     -> b2-032 Loop-2 (bank 1: Noise (Loop))
    {110,   0,   0, 110},  // 177 Engine (Loop) #        -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 178 Tyre Screech (Loop) #  -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 179 Siren (Loop) #         -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 180 Helicopter (Loop) #    -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 181 Dog Bark (Loop) #      -> b1-111 Noise (Loop)
    {110,   0,   0, 110},  // 182 Car Pass (Loop) #      -> b1-111 Noise (Loop)
    { 98,   0,   0,  98},  // 183 Male Voice (Loop) #    -> b1-099 Male Voice-1 (Loop)
    {160,   0,   0, 110},  // 184 Machine Gun (Loop) #   -> b2-033 Loop-3 (bank 1: Noise (Loop))
    {110,   0,   0, 110},  // 185 Starship (Loop) #      -> b1-111 Noise (Loop)
    {222,   0,   0, 110},  // 186 Jam-1 (Loop)           -> b2-095 Jam-1 (Loop) (bank 1: Noise (Loop))
    {223,   0,   0, 110},  // 187 Jam-2 (Loop)           -> b2-096 Jam-2 (Loop) (bank 1: Noise (Loop))
    {224,   0,   0, 110},  // 188 Jam-3 (Loop)           -> b2-097 Jam-3 (Loop) (bank 1: Noise (Loop))
    {225,   0,   0, 110},  // 189 Jam-4 (Loop)           -> b2-098 Jam-4 (Loop) (bank 1: Noise (Loop))
    {226,   0,   0, 110},  // 190 Jam-5 (Loop)           -> b2-099 Jam-5 (Loop) (bank 1: Noise (Loop))
    {227,   0,   0, 110},  // 191 Jam-6 (Loop)           -> b2-100 Jam-6 (Loop) (bank 1: Noise (Loop))
    {228,   0,   0, 110},  // 192 Jam-7 (Loop)           -> b2-101 Jam-7 (Loop) (bank 1: Noise (Loop))
    {229,   0,   0, 110},  // 193 Jam-8 (Loop)           -> b2-102 Jam-8 (Loop) (bank 1: Noise (Loop))
    {230,   0,   0, 110},  // 194 Jam-9 (Loop)           -> b2-103 Jam-9 (Loop) (bank 1: Noise (Loop))
    {231,   0,   0, 110},  // 195 Jam-10 (Loop)          -> b2-104 Jam-10 (Loop) (bank 1: Noise (Loop))
    {232,   0,   0, 110},  // 196 Jam-11 (Loop)          -> b2-105 Jam-11 (Loop) (bank 1: Noise (Loop))
    {233,   0,   0, 110},  // 197 Jam-12 (Loop)          -> b2-106 Jam-12 (Loop) (bank 1: Noise (Loop))
    {234,   0,   0, 110},  // 198 Jam-13 (Loop)          -> b2-107 Jam-13 (Loop) (bank 1: Noise (Loop))
    {235,   0,   0, 110},  // 199 Jam-14 (Loop)          -> b2-108 Jam-14 (Loop) (bank 1: Noise (Loop))
    {236,   0,   0, 110},  // 200 Jam-15 (Loop)          -> b2-109 Jam-15 (Loop) (bank 1: Noise (Loop))
    {237,   0,   0, 110},  // 201 Jam-16 (Loop)          -> b2-110 Jam-16 (Loop) (bank 1: Noise (Loop))
    {238,   0,   0, 110},  // 202 Jam-17 (Loop)          -> b2-111 Jam-17 (Loop) (bank 1: Noise (Loop))
    {239,   0,   0, 110},  // 203 Jam-18 (Loop)          -> b2-112 Jam-18 (Loop) (bank 1: Noise (Loop))
    {240,   0,   0, 110},  // 204 Jam-19 (Loop)          -> b2-113 Jam-19 (Loop) (bank 1: Noise (Loop))
    {241,   0,   0, 110},  // 205 Jam-20 (Loop)          -> b2-114 Jam-20 (Loop) (bank 1: Noise (Loop))
    {242,   0,   0, 110},  // 206 Jam-21 (Loop)          -> b2-115 Jam-21 (Loop) (bank 1: Noise (Loop))
    {243,   0,   0, 110},  // 207 Jam-22 (Loop)          -> b2-116 Jam-22 (Loop) (bank 1: Noise (Loop))
    {244,   0,   0, 110},  // 208 Jam-23 (Loop)          -> b2-117 Jam-23 (Loop) (bank 1: Noise (Loop))
    {245,   0,   0, 110},  // 209 Jam-24 (Loop)          -> b2-118 Jam-24 (Loop) (bank 1: Noise (Loop))
    {246,   0,   0, 110},  // 210 Jam-25 (Loop)          -> b2-119 Jam-25 (Loop) (bank 1: Noise (Loop))
    {247,   0,   0, 110},  // 211 Jam-26 (Loop)          -> b2-120 Jam-26 (Loop) (bank 1: Noise (Loop))
    {248,   0,   0, 110},  // 212 Jam-27 (Loop)          -> b2-121 Jam-27 (Loop) (bank 1: Noise (Loop))
    {249,   0,   0, 110},  // 213 Jam-28 (Loop)          -> b2-122 Jam-28 (Loop) (bank 1: Noise (Loop))
    {250,   0,   0, 110},  // 214 Jam-29 (Loop)          -> b2-123 Jam-29 (Loop) (bank 1: Noise (Loop))
    {251,   0,   0, 110},  // 215 Jam-30 (Loop)          -> b2-124 Jam-30 (Loop) (bank 1: Noise (Loop))
    {252,   0,   0, 110},  // 216 Jam-31 (Loop)          -> b2-125 Jam-31 (Loop) (bank 1: Noise (Loop))
    {253,   0,   0, 110},  // 217 Jam-32 (Loop)          -> b2-126 Jam-32 (Loop) (bank 1: Noise (Loop))
    {254,   0,   0, 110},  // 218 Jam-33 (Loop)          -> b2-127 Jam-33 (Loop) (bank 1: Noise (Loop))
    {255,   0,   0, 110},  // 219 Jam-34 (Loop)          -> b2-128 Jam-34 (Loop) (bank 1: Noise (Loop))
    {222,   0,   0, 110},  // 220 Jam-35 (Loop)          -> b2-095 Jam-1 (Loop) (bank 1: Noise (Loop))
    {223,   0,   0, 110},  // 221 Jam-36 (Loop)          -> b2-096 Jam-2 (Loop) (bank 1: Noise (Loop))
    {224,   0,   0, 110},  // 222 Jam-37 (Loop)          -> b2-097 Jam-3 (Loop) (bank 1: Noise (Loop))
    {225,   0,   0, 110},  // 223 Jam-38 (Loop)          -> b2-098 Jam-4 (Loop) (bank 1: Noise (Loop))
    {226,   0,   0, 110},  // 224 Jam-39 (Loop)          -> b2-099 Jam-5 (Loop) (bank 1: Noise (Loop))
    {227,   0,   0, 110},  // 225 Jam-40 (Loop)          -> b2-100 Jam-6 (Loop) (bank 1: Noise (Loop))
    {111,   0,   0, 111},  // 226 Shot-1                 -> b1-112 Shot-1
    {112,   0,   0, 112},  // 227 Shot-2                 -> b1-113 Shot-2
    {113,   0,   0, 113},  // 228 Shot-3                 -> b1-114 Shot-3
    {114,   0,   0, 114},  // 229 Shot-4                 -> b1-115 Shot-4
    {115,   0,   0, 115},  // 230 Shot-5                 -> b1-116 Shot-5
    {116,   0,   0, 116},  // 231 Shot-6                 -> b1-117 Shot-6
    {117,   0,   0, 117},  // 232 Shot-7                 -> b1-118 Shot-7
    {118,   0,   0, 118},  // 233 Shot-8                 -> b1-119 Shot-8
    {119,   0,   0, 119},  // 234 Shot-9                 -> b1-120 Shot-9
    {120,   0,   0, 120},  // 235 Shot-10                -> b1-121 Shot-10
    {121,   0,   0, 121},  // 236 Shot-11                -> b1-122 Shot-11
    {122,   0,   0, 122},  // 237 Shot-12                -> b1-123 Shot-12
    {123,   0,   0, 123},  // 238 Shot-13                -> b1-124 Shot-13
    {124,   0,   0, 124},  // 239 Shot-14                -> b1-125 Shot-14
    {125,   0,   0, 125},  // 240 Shot-15                -> b1-126 Shot-15
    {126,   0,   0, 126},  // 241 Shot-16                -> b1-127 Shot-16
    {127,   0,   0, 127},  // 242 Shot-17                -> b1-128 Shot-17
    {111,   0,   0, 111},  // 243 Shot-18                -> b1-112 Shot-1
    {112,   0,   0, 112},  // 244 Shot-19                -> b1-113 Shot-2
    {113,   0,   0, 113},  // 245 Shot-20                -> b1-114 Shot-3
    {114,   0,   0, 114},  // 246 Shot-21                -> b1-115 Shot-4
    {115,   0,   0, 115},  // 247 Shot-22                -> b1-116 Shot-5
    {116,   0,   0, 116},  // 248 Shot-23                -> b1-117 Shot-6
    {117,   0,   0, 117},  // 249 Shot-24                -> b1-118 Shot-7
    {118,   0,   0, 118},  // 250 Shot-25                -> b1-119 Shot-8
    {119,   0,   0, 119},  // 251 Shot-26                -> b1-120 Shot-9
    { 79,   0,   0,  79},  // 252 Alto Sax               -> b1-080 Sax-2 (Loop)
    { 44,   0,  43,  44},  // 253 Shakuhachi             -> b1-045 Breath
    { 47,  12,   0,  47},  // 254 Marimba                -> b1-048 Marimba
    {110,   0,   0, 110},  // 255 Dog Bark               -> b1-111 Noise (Loop)
};

const Mt32Translator::WaveFallback kWaveFallbacks[] = {
    { 93,  34, -12,   0},  // Keypress (loop)        -> b1-035 Piano Forte Thump
    { 95,  77,  12,   0},  // Trombone (loop)        -> b1-078 Trombone (Loop)
    { 96,  76,   0,   0},  // Trumpet (loop)         -> b1-077 Trumpet (Loop)
    { 97,  80,  12,   0},  // Clarinet (loop)        -> b1-081 Reed (Loop)
    { 98,  41, -12,   0},  // Flute (loop)           -> b1-042 Flute Low
    {105,  49, -12,   0},  // Xylophone (loop)       -> b1-050 Xylophone Low
    {106,  51, -36, -34},  // Tubular Bells (loop)   -> b1-052 Wind Bell
    {112,  66, -12,   0},  // Pizzicato (loop)       -> b1-067 Pizzicato
    {113,  67, -24,   0},  // Harp (loop)            -> b1-068 Harp
    {118,  43, -12, -12},  // Flute 2 (loop)         -> b1-044 Indian Flute
};

// The MT-32's rhythm timbres keep the D-series' drum kit where tones use another wave: El. Snare # (R6 Elec SD) stays on
// Snare Drum-2*, like the rhythm keys' stand-in (r20 SnareDrum2), while tones play that sample as Snare Drum-1* 4 up
// (VOICE_MT.DAT's E-TOM; the user's choice, as for the tuned El. Snare).
struct DrumKitWave {
    uint8_t mt32Wave;
    Mt32Translator::WaveMapping mapping;
};
const DrumKitWave kDrumKitWaves[] = {
    {56, {132, 0, 0, 4}},  // El. Snare Drum # -> b2-005 Snare Drum-2* (bank 1: Snare Drum-2)
};

// Roomy toms: the MT-32's tom sample (Tom Tom-2) becomes Tom Tom-1, tuned as Roland tuned the TomTom1 set against the
// TomTom2 set (about 2.4 semitones up).
const Mt32Translator::WaveFallback kRoomyToms[] = {
    {3, 7, 2, 40},     // Electric Tom -> Tom Tom-1
    {57, 135, 2, 40},  // Ac. Tom # -> Tom Tom-1*
};

// MT-32 preset timbres A1-B64 -> D-110 stand-ins (tone as group * 64 + number: a11-a88 = 0-63, b11-b88 = 64-127,
// r01-r64 = 192-255) with a key shift, and whether the MT-32's own timbre is preferred (see PresetMode::Hybrid). Chosen
// by comparing the MT-32's presets (translated) with the D-110's partial by partial and by rendering both at key 60
// (fundamental and spectral centroid), then by the user's ear on a real D-20 (their choices: Elec Org 3 on ElecOrgan1,
// Pipe Org 3 +12, Syn Bass 2 on Harpsi 2, Str Sect 3 on Strings 1, Bassoon on Sax 2 +12, Shakuhachi on Flute 1 -12,
// Timpani +12, Schooldaze on Space Horn, Triangle +12, Syn Brass 3 on Syn Lead 2). Many D-110 presets are MT-32 presets
// with partials added (Syn Brass 1 is the much richer Brass 1, Syn Brass 4 is Steam Pad plus a Steamer attack) or an
// octave or two away, which the key shift undoes. Some have no D-series counterpart (Elec Org 3 and 4, Elec Gtr 2 - the
// MT-32's is a clear guitar, the D-series' distorted with feedback - Doctor Solo, Shakuhachi), and the bells (Windbell,
// Tube Bell, Triangle, WaterBells) play the D-series' Wind Bell sample, the MT-32's Tubular Bells, far from where the
// MT-32's own play it exactly: these prefer the MT-32's own timbre (Hybrid mode).
struct StandIn {
    uint8_t tone;
    int8_t keyShift;
    bool exactPreferred = false;
};
constexpr bool kExact = true;
const StandIn kPresets[128] = {
    {0, 0}, {1, 0}, {2, 0}, {4, 0}, {5, 12}, {6, 0}, {7, 0}, {3, 0},            // AcouPiano1-3, ElecPiano1-4, Honkytonk
    {8, 0}, {9, 0}, {8, 0, kExact}, {11, 0, kExact}, {12, 12}, {13, 0}, {14, 12}, {15, 0},  // Elec Org 1-4 (3: ElecOrgan1), Pipe Org 1-3, Accordion
    {16, 0}, {17, 0}, {18, 0}, {19, 0}, {20, 12}, {21, 0}, {22, 0}, {23, 0},    // Harpsi 1-3, Clavi 1-3, Celesta 1-2
    {36, 0}, {37, 0}, {81, 0}, {78, 0},     // Syn Brass1-2 (Brass 1-2), Syn Brass3 (Syn Lead 2), Syn Brass4 (Steam Pad)
    {91, 12}, {17, 0}, {86, 12}, {87, 12},   // Syn Bass 1 (ElecBass 2), Syn Bass 2 (Harpsi 2), Syn Bass 3-4
    {64, 0}, {65, -12}, {66, 0}, {67, 0}, {68, 0}, {69, 0}, {70, 0}, {77, 0},   // Fantasy, Harmo Pan ... Warm Bell, Funny Vox (Reso Synth)
    {72, 0}, {73, 0}, {74, 0}, {75, 0}, {79, 0, kExact}, {71, 0}, {76, 0}, {83, 0},  // Echo Bell ... Echo Pan, DoctorSolo (VibeString), Schooldaze (Space Horn), Bellsinger (Bell Swing), SquareWave (Syn Lead 4)
    {32, 0}, {34, 0}, {32, 0}, {29, 0}, {24, 0}, {25, 0}, {26, 0}, {27, 0},     // Str Sect 1-3 (Strings 1, 3, 1: 2 and 4 attack slowly), Pizzicato, Violin 1-2, Cello 1-2
    {28, 12}, {30, -12}, {30, -12}, {100, 0}, {101, 0}, {102, 0}, {103, 0, kExact}, {110, 0},  // Contrabass, Harp 1-2 (Harp 1), Guitar 1-2, Elec Gtr 1-2, Sitar
    {88, 12}, {89, 12}, {90, 12}, {91, 12}, {92, 12}, {93, 12}, {94, 12}, {94, 12},  // Acou Bass1-2, Elec Bass1-2, Slap Bass1-2, Fretless 1-2 (Fretless 1)
    {48, -12}, {49, -12}, {50, -12}, {50, 0}, {51, 0}, {52, -12}, {56, 0}, {57, 12},  // Flute 1-2, Piccolo 1-2, Recorder, Pan Pipes, Sax 1-2
    {58, 24}, {56, 0}, {59, 0}, {59, 0}, {61, 12}, {46, 0}, {57, 12}, {63, 0},  // Sax 3-4, Clarinet 1-2 (Clarinet 1), Oboe, Engl Horn, Bassoon (Sax 2), Harmonica
    {40, 0}, {41, -12}, {42, 0}, {43, 0}, {45, 0}, {45, 0}, {47, 0}, {39, 0},   // Trumpet 1-2, Trombone 1-2, Fr Horn 1-2 (Fr Horn), Tuba, Brs Sect 1 (Brass 4)
    {38, 0}, {96, -12}, {96, -12}, {79, 0}, {118, -12, kExact}, {97, 0}, {119, 0, kExact}, {99, 0},  // Brs Sect 2 (Brass 3), Vibe 1-2, Syn Mallet (VibeString), Windbell, Glock, Tube Bell, Xylophone
    {98, 12}, {104, 0}, {107, 0}, {48, -12, kExact}, {55, 0}, {55, 0}, {53, 0}, {54, 0},  // Marimba, Koto, Sho, Shakuhachi (Flute 1), Whistle 1-2, Bottleblow, Breathpipe
    {116, 12}, {113, 0}, {112, 0}, {112, 0}, {113, 0}, {109, 0}, {216, 0}, {196, 0},  // Timpani, MelodicTom, Deep Snare, Elec Perc1-2, Taiko, Taiko Rim (r25 Rim Shot), Cymbal (r05)
    {248, 0}, {117, 12, kExact}, {120, 0}, {123, 0}, {121, 0}, {122, 0}, {126, 0, kExact}, {127, 0},  // Castanets (r57), Triangle (+12), Orche Hit, Telephone, Bird Tweet, OneNoteJam, WaterBells, JungleTune
};

// MT-32 rhythm timbres R1-R64 -> D-110 rhythm tones r01-r64. R31-R63 are the CM-32L's sound effects.
constexpr uint8_t kOff = Mt32Translator::kRhythmOff;
const uint8_t kRhythm[64] = {
    14, 18, 30, 31, 32, 19, 0, 2,          // Acou BD, Acou SD, Acou Hi/Mid/Low Tom (TomTom2: the same sample and pitches), Elec SD, Clsd HiHat, OpenHiHat1
    4, 7, 24, 38, 40, 43, 44, 45,          // Crash Cym, Ride Cym, Rim Shot, Hand Clap, Cowbell, Mt HiConga, High/Low Conga
    46, 47, 41, 42, 48, 49, 39, 55,        // Hi/Low Timbale, High/Low Bongo, High/Low Agogo, Tambourine, Claves
    51, 53, 52, 50, 54, 3, kOff, kOff,     // Maracas, Samba Whistle L/S, Cabasa, Quijada, OpenHiHat2, Laughing, Screaming
    15, 17, 32, 31, kOff, kOff, kOff, kOff,  // Punch, Heartbeat, Footsteps 1-2 (bass drums, toms), Applause, Creaking, Door, Scratch
    57, kOff, kOff, kOff, 4, kOff, kOff, kOff,  // Windchime (Triangle), Engine, Car-stop, Car-pass, Crash, Siren, Train, Jet
    kOff, kOff, 20, 18, kOff, 12, kOff, 58,  // Helicopter, Starship, Pistol, Machinegun (snares), Lasergun, Explosion (China), Dog, Horse (Wood Block)
    kOff, kOff, kOff, kOff, kOff, kOff, kOff, kOff,  // Birds, Rain, Thunder, Wind, Waves, Stream, Bubble, none
};

// The MT-32's power-on setup (from its owner's manual).
constexpr uint8_t kPowerOnPrograms[8] = {68, 48, 95, 78, 41, 3, 110, 122};  // Slap Bass 1, Str Sect 1, Brs Sect 1, Sax 1, Ice Rain, Elec Piano 1, Bottle Blow, Orche Hit
constexpr int8_t kPowerOnPans[8] = {0, 0, 0, 0, 4, -4, 7, -7};              // Right of centre > 0
constexpr uint8_t kPowerOnReserves[9] = {3, 10, 6, 4, 3, 0, 0, 0, 6};
struct RhythmKey {
    uint8_t key;
    uint8_t timbre;  // R1-R30 as 0-29
    int8_t pan;      // Right of centre > 0
};
constexpr RhythmKey kPowerOnRhythm[] = {
    {35, 0, 0}, {36, 0, 0}, {37, 10, 1}, {38, 1, 0}, {39, 11, -1}, {40, 5, 1}, {41, 4, -4}, {42, 6, 1},
    {43, 4, -4}, {44, 29, 1}, {45, 3, -1}, {46, 7, 1}, {47, 3, -1}, {48, 2, 4}, {49, 8, 1}, {50, 2, 4},
    {51, 9, -1}, {54, 22, -2}, {56, 12, 0}, {60, 18, 5}, {61, 19, 3}, {62, 13, -1}, {63, 14, -2}, {64, 15, -3},
    {65, 16, 0}, {66, 17, 2}, {67, 20, 5}, {68, 21, 5}, {69, 27, -2}, {70, 24, 3}, {71, 26, -2}, {72, 25, -2},
    {73, 28, -3}, {75, 23, -5},
};

// MT-32 panpot (0 = right) for a position right of centre.
uint8_t mt32Pan(int right) {
    return uint8_t(std::clamp(7 - right, 0, 14));
}

uint8_t checksum(const uint8_t* data, size_t length) {
    unsigned sum = 0;
    for (size_t i = 0; i < length; i++) sum += data[i];
    return uint8_t((128 - sum % 128) % 128);
}

void appendDataSet(std::vector<uint8_t>& out, uint8_t deviceId, uint32_t address, const uint8_t* data, size_t length) {
    const size_t start = out.size();
    const uint8_t header[] = {0xF0, 0x41, deviceId, 0x16, 0x12, uint8_t((address >> 14) & 0x7F), uint8_t((address >> 7) & 0x7F),
                              uint8_t(address & 0x7F)};
    out.insert(out.end(), header, header + sizeof(header));
    out.insert(out.end(), data, data + length);
    out.push_back(checksum(&out[start + 5], 3 + length));
    out.push_back(0xF7);
}

bool inMt32Area(uint32_t address) {
    return (address >= kPatchTemp && address < kRhythmSetupEnd) || (address >= kToneTemp && address < kToneTempEnd) ||
           (address >= kPatchMemory && address < kPatchMemoryEnd) || (address >= kToneMemory && address < kToneMemoryEnd) ||
           (address >= kSystem && address < kSystem + kSystemSize) || (address >= kDisplay && address < kDisplay + 0x4000) ||
           address >= kReset;
}

}  // namespace

void Mt32Translator::Output::set(uint32_t address, uint8_t value) {
    if (bytes.empty()) {
        start = address;
    } else if (address < start) {
        bytes.insert(bytes.begin(), size_t(start - address), int16_t(-1));
        start = address;
    }
    const size_t index = size_t(address - start);
    if (index >= bytes.size()) bytes.resize(index + 1, int16_t(-1));
    bytes[index] = value;
}

Mt32Translator::Mt32Translator() {
    for (uint8_t part = 0; part < 9; part++) unitChannels_[part] = part < 8 ? part : 9;  // D-20: 1-8, rhythm 10
    resetPresetChoices();
    reset();
}

void Mt32Translator::setTarget(Target target) {
    target_ = target;
}

void Mt32Translator::setUnitChannels(const uint8_t* channels) {
    for (size_t part = 0; part < 9; part++) unitChannels_[part] = std::min<uint8_t>(channels[part], 16);
}

void Mt32Translator::setMemoryInUnit(bool enabled) {
    memoryInUnit_ = enabled;
}

void Mt32Translator::setMasterVolumeAsVolume(bool enabled) {
    masterVolumeAsVolume_ = enabled;
}

uint8_t Mt32Translator::mt32Channel(int part) const {
    return system_[kSystemChannels + size_t(std::clamp(part, 0, 8))];
}

uint8_t Mt32Translator::unitChannel(int part) const {
    return target_ == Target::D20 ? unitChannels_[size_t(std::clamp(part, 0, 8))] : mt32Channel(part);
}

void Mt32Translator::unitChannelsFor(uint8_t channel, std::vector<uint8_t>& out) const {
    out.clear();
    if (target_ != Target::D20) {
        out.push_back(channel);  // The unit's parts follow the MT-32 channels (system area)
        return;
    }
    for (size_t part = 0; part < 9; part++) {
        if (system_[kSystemChannels + part] != channel) continue;
        const uint8_t unit = unitChannels_[part];
        if (unit < 16 && std::find(out.begin(), out.end(), unit) == out.end()) out.push_back(unit);
    }
}

uint8_t Mt32Translator::scaledVolume(uint8_t channel) const {
    const unsigned master = masterVolumeAsVolume_ ? std::min<unsigned>(system_[kSystemMasterVolume], 100) : 100;
    return uint8_t((volume_[channel & 15] * master + 50) / 100);
}

void Mt32Translator::appendVolumes(std::vector<uint32_t>& out) const {
    std::vector<uint8_t> units;
    bool done[16] = {};
    for (size_t part = 0; part < 9; part++) {
        const uint8_t channel = system_[kSystemChannels + part];
        if (channel >= 16 || done[channel]) continue;
        done[channel] = true;
        unitChannelsFor(channel, units);
        for (uint8_t unit : units) out.push_back(uint32_t(0xB0 | unit) | (7u << 8) | (uint32_t(scaledVolume(channel)) << 16));
    }
}

const Mt32Translator::WaveMapping& Mt32Translator::waveMapping(int mt32Wave, bool drumKit) {
    if (drumKit) {
        for (const DrumKitWave& drum : kDrumKitWaves) {
            if (drum.mt32Wave == (mt32Wave & 0xFF)) return drum.mapping;
        }
    }
    return kWaves[mt32Wave & 0xFF];
}

void Mt32Translator::translatePcm(int mt32Wave, uint8_t coarse, uint8_t fine, uint8_t& wave, uint8_t& outCoarse, uint8_t& outFine,
                                  bool roomyToms, bool drumKit) {
    // Adds a correction in cents, carrying whole semitones from the fine pitch (0-100, 50 = none) into the coarse.
    auto correct = [&](int8_t addCoarse, int8_t addFine) {
        const int cents = (int(coarse) + addCoarse) * 100 + int(std::min<uint8_t>(fine, 100)) - 50 + addFine;
        const int semitones = cents + 50 >= 0 ? (cents + 50) / 100 : -((49 - cents) / 100);  // Rounded to nearest
        outCoarse = uint8_t(std::clamp(semitones, 0, 96));
        outFine = uint8_t(std::clamp(cents - int(outCoarse) * 100 + 50, 0, 100));
        return semitones >= 0 && semitones <= 96;
    };
    if (roomyToms) {
        for (const WaveFallback& tom : kRoomyToms) {
            if (tom.mt32Wave != (mt32Wave & 0xFF)) continue;
            wave = tom.wave;
            correct(tom.coarse, tom.fine);
            return;
        }
    }
    const WaveMapping& mapping = waveMapping(mt32Wave, drumKit);
    wave = mapping.wave;
    if (correct(mapping.coarse, mapping.fine)) return;
    for (const WaveFallback& fallback : kWaveFallbacks) {
        if (fallback.mt32Wave != (mt32Wave & 0xFF)) continue;
        const uint8_t clampedCoarse = outCoarse, clampedFine = outFine;
        if (correct(fallback.coarse, fallback.fine)) {
            wave = fallback.wave;
        } else {
            outCoarse = clampedCoarse;  // Out of range either way: keep the primary wave, clamped
            outFine = clampedFine;
        }
        return;
    }
}

void Mt32Translator::setPresets(std::shared_ptr<const Mt32Presets> presets) {
    presets_ = presets && presets->valid() ? std::move(presets) : nullptr;
}

void Mt32Translator::setPresetMode(PresetMode mode) {
    mode_ = mode;
}

void Mt32Translator::setPresetBanks(bool enabled) {
    presetBanks_ = enabled;
}

Mt32Translator::PresetMode Mt32Translator::presetMode() const {
    return presets_ ? mode_ : PresetMode::StandIns;
}

Mt32Translator::PresetChoice Mt32Translator::defaultPresetChoice(int mt32Timbre) {
    const StandIn& standIn = kPresets[mt32Timbre & 0x7F];
    PresetChoice choice;
    choice.tone = standIn.tone;
    choice.keyShift = standIn.keyShift;
    choice.exact = standIn.exactPreferred;
    return choice;
}

void Mt32Translator::setPresetChoice(int mt32Timbre, const PresetChoice& choice) {
    PresetChoice checked = choice;
    if (checked.tone >= 128 && checked.tone < 192) checked.tone = defaultPresetChoice(mt32Timbre).tone;  // No i tones
    checked.keyShift = int8_t(std::clamp<int>(checked.keyShift, -24, 24));
    presetChoices_[size_t(mt32Timbre & 0x7F)] = checked;
}

void Mt32Translator::resetPresetChoices() {
    for (int timbre = 0; timbre < 128; timbre++) presetChoices_[size_t(timbre)] = defaultPresetChoice(timbre);
}

const Mt32Translator::PresetChoice& Mt32Translator::presetChoice(int mt32Timbre) const {
    return presetChoices_[size_t(mt32Timbre & 0x7F)];
}

void Mt32Translator::setRhythmChoice(int mt32RhythmTimbre, const RhythmChoice& choice) {
    RhythmChoice checked = choice;
    if (checked.tone < -1 || checked.tone > int(kRhythmOff)) checked.tone = -1;
    rhythmChoices_[size_t(mt32RhythmTimbre & 0x3F)] = checked;
}

void Mt32Translator::resetRhythmChoices() {
    rhythmChoices_.fill(RhythmChoice());
}

const Mt32Translator::RhythmChoice& Mt32Translator::rhythmChoice(int mt32RhythmTimbre) const {
    return rhythmChoices_[size_t(mt32RhythmTimbre & 0x3F)];
}

bool Mt32Translator::presetIsExact(int mt32Timbre) const {
    if (!presets_) return false;
    if (mode_ == PresetMode::Exact) return true;
    return mode_ == PresetMode::Hybrid && presetChoices_[size_t(mt32Timbre & 0x7F)].exact;
}

bool Mt32Translator::rhythmIsExact(int mt32RhythmTimbre) const {
    const int timbre = mt32RhythmTimbre & 0x3F;
    if (!presets_ || size_t(timbre) >= presets_->rhythm.size()) return false;
    if (mode_ == PresetMode::Exact) return true;
    return mode_ == PresetMode::Hybrid && rhythmChoices_[size_t(timbre)].exact;
}

int Mt32Translator::rhythmStandIn(int mt32RhythmTimbre) const {
    const RhythmChoice& choice = rhythmChoices_[size_t(mt32RhythmTimbre & 0x3F)];
    return choice.tone >= 0 ? choice.tone : rhythmToneFor(mt32RhythmTimbre);
}

namespace {

std::vector<std::string> splitChoices(const std::string& text) {
    std::vector<std::string> entries;
    size_t start = 0;
    while (start <= text.size()) {
        const size_t end = std::min(text.find(';', start), text.size());
        if (end > start) entries.push_back(text.substr(start, end - start));
        start = end + 1;
    }
    return entries;
}

}  // namespace

std::string Mt32Translator::presetChoicesText(const PresetChoices& choices) {
    std::string text;
    for (int timbre = 0; timbre < 128; timbre++) {
        const PresetChoice& choice = choices[size_t(timbre)];
        if (choice == defaultPresetChoice(timbre)) continue;
        if (!text.empty()) text += ';';
        text += std::to_string(timbre) + ':' + std::to_string(choice.tone) + ':' + std::to_string(choice.keyShift) + ':' + (choice.exact ? '1' : '0');
    }
    return text;
}

void Mt32Translator::parsePresetChoices(const std::string& text, PresetChoices& choices) {
    for (int timbre = 0; timbre < 128; timbre++) choices[size_t(timbre)] = defaultPresetChoice(timbre);
    for (const std::string& entry : splitChoices(text)) {
        int timbre = 0, tone = 0, shift = 0, exact = 0;
        if (std::sscanf(entry.c_str(), "%d:%d:%d:%d", &timbre, &tone, &shift, &exact) != 4 || timbre < 0 || timbre > 127) continue;
        if (tone < 0 || tone > 255 || (tone >= 128 && tone < 192)) continue;
        PresetChoice choice;
        choice.tone = uint8_t(tone);
        choice.keyShift = int8_t(std::clamp(shift, -24, 24));
        choice.exact = exact != 0;
        choices[size_t(timbre)] = choice;
    }
}

std::string Mt32Translator::rhythmChoicesText(const RhythmChoices& choices) {
    std::string text;
    for (int timbre = 0; timbre < 64; timbre++) {
        const RhythmChoice& choice = choices[size_t(timbre)];
        if (choice == RhythmChoice()) continue;
        if (!text.empty()) text += ';';
        text += std::to_string(timbre) + ':' + std::to_string(choice.tone) + ':' + (choice.exact ? '1' : '0');
    }
    return text;
}

void Mt32Translator::parseRhythmChoices(const std::string& text, RhythmChoices& choices) {
    choices.fill(RhythmChoice());
    for (const std::string& entry : splitChoices(text)) {
        int timbre = 0, tone = 0, exact = 0;
        if (std::sscanf(entry.c_str(), "%d:%d:%d", &timbre, &tone, &exact) != 3 || timbre < 0 || timbre > 63) continue;
        if (tone < -1 || tone > int(kRhythmOff)) continue;
        RhythmChoice choice;
        choice.tone = int8_t(tone);
        choice.exact = exact != 0;
        choices[size_t(timbre)] = choice;
    }
}

void Mt32Translator::setRoomyToms(bool enabled) {
    roomyToms_ = enabled;
}

void Mt32Translator::resend(uint8_t deviceId, std::vector<uint8_t>& out) {
    std::vector<uint32_t> shortAfter;
    std::vector<uint8_t> patches(128 * 8);
    for (size_t patch = 0; patch < 128; patch++) std::memcpy(&patches[patch * 8], patchMemory_[patch].data(), 8);
    for (uint32_t offset = 0; offset < patches.size(); offset += 256) {
        translateWrite(kPatchMemory + offset, &patches[offset], 256, deviceId, out, shortAfter);
    }
    std::vector<uint8_t> rhythm(85 * 4);
    for (size_t key = 0; key < 85; key++) std::memcpy(&rhythm[key * 4], rhythmSetup_[key].data(), 4);
    translateWrite(kRhythmSetup, rhythm.data(), 256, deviceId, out, shortAfter);
    translateWrite(kRhythmSetup + 256, rhythm.data() + 256, rhythm.size() - 256, deviceId, out, shortAfter);
    uint8_t temps[9 * 16];
    for (size_t part = 0; part < 9; part++) std::memcpy(&temps[part * 16], patchTemp_[part].data(), 16);
    translateWrite(kPatchTemp, temps, sizeof(temps), deviceId, out, shortAfter);
}

void Mt32Translator::unitTone(const Tone& tone, uint8_t* out) const {
    Output output;
    for (uint32_t offset = 0; offset < kToneSize; offset++) translateTone(tone, 0, offset, output);
    for (size_t i = 0; i < kToneSize; i++) out[i] = i < output.bytes.size() && output.bytes[i] >= 0 ? uint8_t(output.bytes[i]) : tone.data[i];
}

void Mt32Translator::convertTone(const uint8_t* mt32Timbre, uint8_t* d110Tone, bool drumKit) const {
    Tone tone;
    std::memcpy(tone.data.data(), mt32Timbre, kToneSize);
    tone.written.set();
    tone.drumKit = drumKit;
    unitTone(tone, d110Tone);
}

int Mt32Translator::presetTone(int mt32Timbre) {
    return kPresets[mt32Timbre & 0x7F].tone;
}

int Mt32Translator::presetKeyShift(int mt32Timbre) {
    return kPresets[mt32Timbre & 0x7F].keyShift;
}

int Mt32Translator::rhythmTone(int mt32RhythmTimbre, bool roomyToms) {
    const int timbre = mt32RhythmTimbre & 0x3F;
    if (roomyToms && timbre >= 2 && timbre <= 4) return 27 + (timbre - 2);  // Acou Hi/Mid/Low Tom -> r28-r30 TomTom1
    return kRhythm[timbre];
}

int Mt32Translator::rhythmToneFor(int mt32RhythmTimbre) const {
    return rhythmTone(mt32RhythmTimbre, roomyToms_);
}

// ---------------------------------------------------------------------------------------------
// Tone cache

void Mt32Translator::setToneCache(int first, int last) {
    cache_.clear();
    cacheFailed_ = false;
    first = std::max(first, 0);
    last = std::min(last, 63);
    if (first <= last) {
        cacheFirst_ = first;
        cache_.resize(size_t(last - first + 1));
    }
    partSlot_.fill(-1);
    slotFill_.fill(false);
    rhythmSlot_.fill(-1);
}

void Mt32Translator::clearToneCache() {
    // Slots that parts or rhythm keys play from stay reserved until they select something else.
    for (CacheSlot& slot : cache_) slot.valid = false;
    cacheFailed_ = false;
}

std::vector<std::vector<uint8_t>> Mt32Translator::toneCacheContents() const {
    std::vector<std::vector<uint8_t>> contents(cache_.size());
    for (size_t i = 0; i < cache_.size(); i++) {
        if (cache_[i].valid) contents[i].assign(cache_[i].tone.begin(), cache_[i].tone.end());
    }
    return contents;
}

void Mt32Translator::restoreToneCache(const std::vector<std::vector<uint8_t>>& contents) {
    for (size_t i = 0; i < cache_.size() && i < contents.size(); i++) {
        if (contents[i].size() != kToneSize) continue;
        std::memcpy(cache_[i].tone.data(), contents[i].data(), kToneSize);
        cache_[i].valid = true;
        cache_[i].lastUse = 0;
    }
}

Mt32Translator::CacheStats Mt32Translator::toneCacheStats() const {
    CacheStats stats;
    stats.slots = int(cache_.size());
    for (const CacheSlot& slot : cache_) stats.used += slot.valid ? 1 : 0;
    stats.hits = cacheHits_;
    stats.misses = cacheMisses_;
    stats.failed = cacheFailed_;
    return stats;
}

int Mt32Translator::cacheFind(const uint8_t* tone) const {
    for (size_t i = 0; i < cache_.size(); i++) {
        if (cache_[i].valid && std::memcmp(cache_[i].tone.data(), tone, kToneSize) == 0) return int(i);
    }
    return -1;
}

int Mt32Translator::cacheAllocate() {
    std::vector<bool> inUse(cache_.size(), false);
    for (int slot : partSlot_) {
        if (slot >= 0) inUse[size_t(slot)] = true;
    }
    for (int slot : rhythmSlot_) {
        if (slot >= 0) inUse[size_t(slot)] = true;
    }
    int oldest = -1;
    for (size_t i = 0; i < cache_.size(); i++) {
        if (inUse[i]) continue;
        if (!cache_[i].valid) return int(i);
        if (oldest < 0 || cache_[i].lastUse < cache_[size_t(oldest)].lastUse) oldest = int(i);
    }
    return oldest;
}

void Mt32Translator::appendToneWrite(int part, int slot, uint8_t deviceId, std::vector<uint8_t>& out) const {
    const uint8_t request[2] = {uint8_t(cacheFirst_ + slot), 0};  // Internal memory
    appendDataSet(out, deviceId, kWriteRequest + uint32_t(part) * 2, request, sizeof(request));
}

void Mt32Translator::resolveSlot(int part) {
    partSlot_[size_t(part)] = -1;
    slotFill_[size_t(part)] = false;
    if (!toneToSend_[size_t(part)] || !cacheActive()) return;
    uint8_t tone[kToneSize];
    unitTone(toneTemp_[size_t(part)], tone);
    int slot = cacheFind(tone);
    if (slot >= 0) {
        cacheHits_++;
        toneToSend_[size_t(part)] = false;  // The timbre temp points at the slot: the unit loads it
        toneSent_[size_t(part)] = true;
    } else {
        slot = cacheAllocate();
        if (slot < 0) return;  // Every slot in use: the tone goes to the part alone
        std::memcpy(cache_[size_t(slot)].tone.data(), tone, kToneSize);
        cache_[size_t(slot)].valid = true;
        slotFill_[size_t(part)] = true;
        cacheMisses_++;
    }
    cache_[size_t(slot)].lastUse = ++cacheClock_;
    partSlot_[size_t(part)] = slot;
}

int Mt32Translator::resolveRhythmKey(int key, uint8_t deviceId, std::vector<uint8_t>& out, bool& borrowed) {
    rhythmSlot_[size_t(key)] = -1;
    const uint8_t value = rhythmSetup_[size_t(key)][0];
    if (!cacheActive() || value >= 64 || !toneMemory_[value].known()) return -1;
    uint8_t tone[kToneSize];
    unitTone(toneMemory_[value], tone);
    int slot = cacheFind(tone);
    if (slot >= 0) {
        cacheHits_++;
    } else {
        slot = cacheAllocate();
        if (slot < 0) return -1;
        std::memcpy(cache_[size_t(slot)].tone.data(), tone, kToneSize);
        cache_[size_t(slot)].valid = true;
        cacheMisses_++;
        // The rhythm part has no tone temp: the tone goes through part 8's, which is restored afterwards.
        Output output;
        for (uint32_t offset = 0; offset < kToneSize; offset++) translateTone(toneMemory_[value], kToneTemp + 7 * kToneSize, offset, output);
        emit(output, deviceId, out);
        appendToneWrite(7, slot, deviceId, out);
        borrowed = true;
    }
    cache_[size_t(slot)].lastUse = ++cacheClock_;
    rhythmSlot_[size_t(key)] = slot;
    return slot;
}

void Mt32Translator::restorePart(int part, uint8_t deviceId, std::vector<uint8_t>& out) {
    // The tone write left the part on the slot it filled: select its own tone again.
    Output output;
    writeByte(kPatchTemp + uint32_t(part) * 16 + kGroup, patchTemp_[size_t(part)][kGroup], output);
    emit(output, deviceId, out);
    if (partSlot_[size_t(part)] < 0 && toneSent_[size_t(part)] && toneTemp_[size_t(part)].known()) {
        Output tone;
        for (uint32_t offset = 0; offset < kToneSize; offset++) {
            translateTone(toneTemp_[size_t(part)], kToneTemp + uint32_t(part) * kToneSize, offset, tone);
        }
        emit(tone, deviceId, out);
    }
}

void Mt32Translator::preloadToneCache(uint8_t deviceId, std::vector<uint8_t>& out) {
    if (!cacheActive()) return;
    bool borrowed = false;
    size_t stored = 0;
    for (size_t number = 0; number < toneMemory_.size() && stored < cache_.size(); number++) {
        if (!toneMemory_[number].known()) continue;
        uint8_t tone[kToneSize];
        unitTone(toneMemory_[number], tone);
        const int found = cacheFind(tone);
        if (found >= 0) {
            cache_[size_t(found)].lastUse = ++cacheClock_;
            stored++;
            continue;
        }
        const int slot = cacheAllocate();
        if (slot < 0) break;
        std::memcpy(cache_[size_t(slot)].tone.data(), tone, kToneSize);
        cache_[size_t(slot)].valid = true;
        cache_[size_t(slot)].lastUse = ++cacheClock_;
        Output output;
        for (uint32_t offset = 0; offset < kToneSize; offset++) translateTone(toneMemory_[number], kToneTemp + 7 * kToneSize, offset, output);
        emit(output, deviceId, out);
        appendToneWrite(7, slot, deviceId, out);
        borrowed = true;
        stored++;
    }
    if (borrowed) restorePart(7, deviceId, out);
}

bool Mt32Translator::writeRequestResult(uint8_t result, uint8_t deviceId, std::vector<uint8_t>& out) {
    if (result == 0 || cache_.empty() || cacheFailed_) return result == 0;
    cacheFailed_ = true;  // The slots do not hold what the translator wrote: stop using them
    for (CacheSlot& slot : cache_) slot.valid = false;
    for (int part = 0; part < 8; part++) {
        if (partSlot_[size_t(part)] < 0) continue;
        partSlot_[size_t(part)] = -1;
        slotFill_[size_t(part)] = false;
        Output output;
        writeByte(kPatchTemp + uint32_t(part) * 16 + kGroup, patchTemp_[size_t(part)][kGroup], output);
        if (toneTemp_[size_t(part)].known()) {
            for (uint32_t offset = 0; offset < kToneSize; offset++) {
                translateTone(toneTemp_[size_t(part)], kToneTemp + uint32_t(part) * kToneSize, offset, output);
            }
        }
        emit(output, deviceId, out);
    }
    Output rhythm;
    for (int key = 0; key < 85; key++) {
        if (rhythmSlot_[size_t(key)] < 0) continue;
        rhythmSlot_[size_t(key)] = -1;
        writeByte(kRhythmSetup + uint32_t(key) * 4, rhythmSetup_[size_t(key)][0], rhythm);
    }
    emit(rhythm, deviceId, out);
    return false;
}

// ---------------------------------------------------------------------------------------------
// Translation

void Mt32Translator::reset() {
    const uint8_t tuneAndReverb[4] = {0x4A, 0, 5, 3};  // Master tune (A = 442 Hz), reverb Room, time 6, level 3
    std::memcpy(system_.data(), tuneAndReverb, sizeof(tuneAndReverb));
    std::memcpy(&system_[kSystemReserves], kPowerOnReserves, sizeof(kPowerOnReserves));
    for (uint32_t part = 0; part < 9; part++) system_[kSystemChannels + part] = uint8_t(part + 1);  // MIDI channels 2-10
    system_[kSystemMasterVolume] = 100;
    for (int patch = 0; patch < 128; patch++) {
        patchMemory_[size_t(patch)] = {uint8_t(patch / 64), uint8_t(patch % 64), 24, 50, 12, 0, 1, 0};
    }
    for (int part = 0; part < 9; part++) {
        std::array<uint8_t, 16>& temp = patchTemp_[size_t(part)];
        temp.fill(0);
        if (part < 8) std::memcpy(temp.data(), patchMemory_[kPowerOnPrograms[part]].data(), 8);
        temp[2] = 24;
        temp[3] = 50;
        temp[4] = 12;
        temp[kReverbSwitch] = 1;
        temp[8] = 80;  // Output level
        temp[kPanpot] = mt32Pan(part < 8 ? kPowerOnPans[part] : 0);
        temp[kKeyRangeUpper] = 127;
    }
    for (std::array<uint8_t, 4>& key : rhythmSetup_) key = {127, 0, 7, 0};  // Unassigned
    for (const RhythmKey& entry : kPowerOnRhythm) {
        rhythmSetup_[size_t(entry.key - 24)] = {uint8_t(64 + entry.timbre), 100, mt32Pan(entry.pan), 1};
    }
    for (Tone& tone : toneTemp_) tone.written.reset();
    for (Tone& tone : toneMemory_) tone.written.reset();
    toneSent_.fill(true);
    toneToSend_.fill(false);
    volume_.fill(127);
    // The cache keeps what the unit's slots hold; nothing plays from them any more.
    partSlot_.fill(-1);
    slotFill_.fill(false);
    rhythmSlot_.fill(-1);
}

void Mt32Translator::powerOn(uint8_t deviceId, std::vector<uint8_t>& out, std::vector<uint32_t>& shortAfter) {
    reset();
    // Memories first, then the system area, then the parts, whose timbre selection loads their tones.
    std::vector<uint8_t> patches(128 * 8);
    for (size_t patch = 0; patch < 128; patch++) std::memcpy(&patches[patch * 8], patchMemory_[patch].data(), 8);
    for (uint32_t offset = 0; offset < patches.size(); offset += 256) {
        translateWrite(kPatchMemory + offset, &patches[offset], 256, deviceId, out, shortAfter);
    }
    std::vector<uint8_t> rhythm(85 * 4);
    for (size_t key = 0; key < 85; key++) std::memcpy(&rhythm[key * 4], rhythmSetup_[key].data(), 4);
    translateWrite(kRhythmSetup, rhythm.data(), 256, deviceId, out, shortAfter);
    translateWrite(kRhythmSetup + 256, rhythm.data() + 256, rhythm.size() - 256, deviceId, out, shortAfter);
    const std::array<uint8_t, kSystemSize> system = system_;
    translateWrite(kSystem, system.data(), system.size(), deviceId, out, shortAfter);
    uint8_t temps[9 * 16];
    for (size_t part = 0; part < 9; part++) std::memcpy(&temps[part * 16], patchTemp_[part].data(), 16);
    translateWrite(kPatchTemp, temps, sizeof(temps), deviceId, out, shortAfter);
    // The patch temp writes above already select the patches; program changes also number them, as the panel shows
    // (only where the unit holds the patch memory).
    std::vector<uint8_t> units;
    for (size_t part = 0; part < 8 && memoryInUnit_; part++) {
        unitChannelsFor(system_[kSystemChannels + part], units);
        for (uint8_t unit : units) shortAfter.push_back(uint32_t(0xC0 | unit) | (uint32_t(kPowerOnPrograms[part]) << 8));
    }
    if (masterVolumeAsVolume_) appendVolumes(shortAfter);
}

void Mt32Translator::translateShort(uint32_t message, uint8_t deviceId, std::vector<uint32_t>& shortOut, std::vector<uint8_t>& sysexAfter) {
    const uint8_t status = uint8_t(message & 0xFF);
    if (status < 0x80) return;
    if (status >= 0xF0) {
        shortOut.push_back(message);
        return;
    }
    const uint8_t channel = status & 0x0F;
    const uint8_t data1 = uint8_t((message >> 8) & 0x7F);
    uint8_t data2 = uint8_t((message >> 16) & 0x7F);
    bool restoreVolume = false;
    switch (status & 0xF0) {
    case 0xB0:
        if (data1 == 10) {
            data2 = uint8_t(127 - data2);  // Pan
        } else if (data1 == 7) {
            volume_[channel] = data2;
            data2 = scaledVolume(channel);
        } else if (data1 == 121) {
            restoreVolume = masterVolumeAsVolume_;  // The MT-32 keeps its volume; D-series units go to full
        }
        break;
    case 0xC0:
        programChange(channel, data1, deviceId, sysexAfter);
        if (!memoryInUnit_) return;  // The unit's own timbre memory is not the MT-32's: the SysEx above is the change
        break;
    default:
        break;
    }
    std::vector<uint8_t> units;
    unitChannelsFor(channel, units);
    for (uint8_t unit : units) {
        shortOut.push_back(uint32_t(status & 0xF0) | unit | (uint32_t(data1) << 8) | (uint32_t(data2) << 16));
        if (restoreVolume) shortOut.push_back(uint32_t(0xB0 | unit) | (7u << 8) | (uint32_t(scaledVolume(channel)) << 16));
    }
}

void Mt32Translator::setPartChannels(const uint8_t* channels) {
    for (size_t part = 0; part < 9; part++) system_[kSystemChannels + part] = std::min<uint8_t>(channels[part], 16);
}

bool Mt32Translator::isDSeriesData(const uint8_t* data, size_t length) {
    for (size_t i = 0; i < length;) {
        if (data[i] != 0xF0) {
            i++;
            continue;
        }
        size_t end = i + 1;
        while (end < length && data[end] != 0xF7) end++;
        if (end >= length) break;
        const size_t size = end + 1 - i;
        const uint8_t* message = data + i;
        i = end + 1;
        if (size < 10 || message[1] != 0x41 || message[3] != 0x16 || (message[4] != 0x12 && message[4] != 0x42)) continue;
        if (message[2] < 0x10) continue;  // Addressed by MIDI channel: MT-32 style
        const uint32_t address = pack(message[5], message[6], message[7]);
        const uint32_t last = address + uint32_t(size - 10) - (size > 10 ? 1 : 0);
        if (!inMt32Area(address) || !inMt32Area(last)) return true;
    }
    return false;
}

void Mt32Translator::translateSysex(const uint8_t* data, size_t length, uint8_t deviceId, std::vector<uint8_t>& out,
                                    std::vector<uint32_t>& shortAfter) {
    const bool rolandWrite = length >= 10 && data[0] == 0xF0 && data[1] == 0x41 && data[3] == 0x16 &&
                             (data[4] == 0x12 || data[4] == 0x42) && data[length - 1] == 0xF7;
    if (!rolandWrite || data[2] > 0x10) {
        // Not an MT-32 write (other models, other unit numbers, data requests): only readdress MT-32 requests.
        const size_t start = out.size();
        out.insert(out.end(), data, data + length);
        if (length >= 5 && data[0] == 0xF0 && data[1] == 0x41 && data[2] == 0x10 && data[3] == 0x16) out[start + 2] = deviceId;
        return;
    }
    if (data[5] == 0x7F) {
        powerOn(deviceId, out, shortAfter);  // Reset, taken before the checksum as mt32emu does
        return;
    }
    if (checksum(data + 5, length - 7) != data[length - 2]) return;  // Damaged: the synth would ignore it too
    uint32_t address = pack(data[5], data[6], data[7]);
    const uint8_t* bytes = data + 8;
    const size_t count = length - 10;
    const uint8_t device = data[2];
    if (device < 0x10) {
        // Addressed by MIDI channel: 00 00 xx is the patch temp area of the part(s) on the channel, 01 xx xx the
        // rhythm setup, 02 xx xx the part's tone. Parts are found as mt32emu does (the rhythm part like part 1).
        if (address >= pack(0x01, 0x00, 0x00) && address < pack(0x02, 0x00, 0x00)) {
            translateWrite(kRhythmSetup + (address - pack(0x01, 0x00, 0x00)), bytes, count, deviceId, out, shortAfter);
            return;
        }
        const bool patch = address < pack(0x01, 0x00, 0x00);
        const bool tone = address >= pack(0x02, 0x00, 0x00) && address < pack(0x03, 0x00, 0x00);
        if (!patch && !tone) return;
        const uint32_t offset = address - (patch ? 0 : pack(0x02, 0x00, 0x00));
        bool found = false;
        for (uint32_t part = 0; part < 9; part++) {
            if (system_[kSystemChannels + part] != device) continue;
            found = true;
            const uint32_t index = part == 8 ? 0 : part;
            translateWrite((patch ? kPatchTemp + index * 16 : kToneTemp + index * kToneSize) + offset, bytes, count, deviceId, out,
                           shortAfter);
        }
        if (!found) translateWrite((patch ? kPatchTemp : kToneTemp) + offset, bytes, count, deviceId, out, shortAfter);
        return;
    }
    translateWrite(address, bytes, count, deviceId, out, shortAfter);
}

// Translates one write of the MT-32 side and appends the unit's messages.
void Mt32Translator::translateWrite(uint32_t address, const uint8_t* data, size_t count, uint8_t deviceId, std::vector<uint8_t>& out,
                                    std::vector<uint32_t>& shortAfter) {
    if (count == 0) return;
    if (address >= kReset) {
        powerOn(deviceId, out, shortAfter);  // The D-series has no reset; set up what the MT-32 resets to
        return;
    }
    if (address >= kDisplay && address < kDisplay + 0x4000) {
        if (address == kDisplay && count <= 32) {
            // The MT-32 shows 20 characters; clear the rest of the D-series' 32.
            uint8_t text[32];
            std::memset(text, ' ', sizeof(text));
            std::memcpy(text, data, count);
            appendDataSet(out, deviceId, kDisplay, text, sizeof(text));
        } else {
            appendDataSet(out, deviceId, address, data, count);
        }
        return;
    }

    // Pass 1: the MT-32 side's memory, so that bytes depending on each other see the whole write.
    std::array<bool, 8> tempWasKnown{};
    std::array<bool, 64> memoryWasKnown{};
    for (size_t i = 0; i < 8; i++) tempWasKnown[i] = toneTemp_[i].known();
    for (size_t i = 0; i < 64; i++) memoryWasKnown[i] = toneMemory_[i].known();
    bool selects[8] = {};
    bool toneEdited[8] = {};
    std::array<bool, 85> rhythmKeys{};
    std::array<bool, 64> memoryChanged{};
    bool masterVolume = false;
    for (size_t i = 0; i < count; i++) {
        const uint32_t a = address + uint32_t(i);
        const uint8_t value = data[i] & 0x7F;
        if (a >= kPatchTemp && a < kRhythmSetup) {
            const uint32_t part = (a - kPatchTemp) / 16, offset = (a - kPatchTemp) % 16;
            patchTemp_[part][offset] = value;
            if (part < 8 && offset <= kNumber) selects[part] = true;
        } else if (a >= kRhythmSetup && a < kRhythmSetupEnd) {
            rhythmSetup_[(a - kRhythmSetup) / 4][(a - kRhythmSetup) % 4] = value;
            if ((a - kRhythmSetup) % 4 == 0) rhythmKeys[(a - kRhythmSetup) / 4] = true;
        } else if (a >= kToneTemp && a < kToneTempEnd) {
            const uint32_t part = (a - kToneTemp) / kToneSize;
            Tone& tone = toneTemp_[part];
            tone.data[(a - kToneTemp) % kToneSize] = value;
            tone.written.set((a - kToneTemp) % kToneSize);
            toneEdited[part] = true;
            partSlot_[part] = -1;  // The part no longer plays a slot's tone as it is
        } else if (a >= kPatchMemory && a < kPatchMemoryEnd) {
            patchMemory_[(a - kPatchMemory) / 8][(a - kPatchMemory) % 8] = value;
        } else if (a >= kToneMemory && a < kToneMemoryEnd && (a - kToneMemory) % 256 < kToneSize) {
            Tone& tone = toneMemory_[(a - kToneMemory) / 256];
            tone.data[(a - kToneMemory) % 256] = value;
            tone.written.set((a - kToneMemory) % 256);
            memoryChanged[(a - kToneMemory) / 256] = true;
        } else if (a >= kSystem && a < kSystem + kSystemSize) {
            system_[a - kSystem] = value;
            if (a - kSystem == kSystemMasterVolume) masterVolume = true;
        }
    }

    // A part whose timbre changed loads it into its tone, as on the MT-32; where it comes from on the unit (a cache
    // slot, or its tone temp) is decided before the unit's bytes, which point at the slot.
    for (int part = 0; part < 8; part++) {
        if (!selects[part]) continue;
        selectTimbre(part);
        resolveSlot(part);
    }
    // Rhythm keys that play memory timbres get them from the cache, also when the MT-32 side rewrote such a timbre.
    bool borrowed = false;
    if (cacheActive()) {
        for (int key = 0; key < 85; key++) {
            const uint8_t value = rhythmSetup_[size_t(key)][0];
            if (value < 64 && memoryChanged[value]) rhythmKeys[size_t(key)] = true;
            if (rhythmKeys[size_t(key)]) resolveRhythmKey(key, deviceId, out, borrowed);
        }
    }

    // Pass 2: the unit's bytes.
    Output output;
    for (size_t i = 0; i < count; i++) writeByte(address + uint32_t(i), data[i] & 0x7F, output);
    for (int key = 0; key < 85; key++) {
        if (rhythmKeys[size_t(key)]) writeByte(kRhythmSetup + uint32_t(key) * 4, rhythmSetup_[size_t(key)][0], output);
    }
    // A tone that is now complete is sent whole, with the pitch corrections its partials could not get so far; so is
    // an edited preset while the target plays a stand-in, which the edit would otherwise change instead.
    for (size_t i = 0; i < 8; i++) {
        if (toneEdited[i] && toneTemp_[i].known() && (!tempWasKnown[i] || !toneSent_[i])) {
            for (uint32_t offset = 0; offset < kToneSize; offset++) translateTone(toneTemp_[i], kToneTemp + uint32_t(i) * kToneSize, offset, output);
            toneSent_[i] = true;
        }
    }
    for (size_t i = 0; i < 64 && memoryInUnit_; i++) {
        if (!memoryWasKnown[i] && toneMemory_[i].known()) {
            for (uint32_t offset = 0; offset < kToneSize; offset++) translateTone(toneMemory_[i], kToneMemory + uint32_t(i) * 256, offset, output);
        }
    }
    emit(output, deviceId, out);
    sendTones(deviceId, out);
    if (borrowed) restorePart(7, deviceId, out);
    if (masterVolume && masterVolumeAsVolume_) appendVolumes(shortAfter);
}

void Mt32Translator::writeByte(uint32_t a, uint8_t value, Output& out) {
    if (a >= kPatchTemp && a < kRhythmSetup) {
        const uint32_t part = (a - kPatchTemp) / 16, offset = (a - kPatchTemp) % 16;
        const uint32_t base = kPatchTemp + part * 16;
        const std::array<uint8_t, 16>& temp = patchTemp_[part];
        if (offset <= kKeyShift && part < 8) {
            // Group and number select a tone (and decide the stand-in's key shift); a key shift alone must not, as
            // that would reload the tone on the unit.
            uint8_t patch[3];
            translatePatch(temp.data(), patch, int(part));
            for (uint32_t i = offset == kKeyShift ? kKeyShift : 0; i < 3; i++) out.set(base + i, patch[i]);
        } else if (offset == kReverbSwitch) {
            out.set(a, std::min<uint8_t>(value, 1));
        } else if (offset == kDummy) {
            out.set(a, 0);  // The MT-32's dummy is d110emu's card and extra-bank flag
        } else if (offset == kPanpot) {
            out.set(a, uint8_t(14 - std::min<uint8_t>(value, 14)));
        } else if (offset == kKeyRangeLower) {
            out.set(a, 0);
        } else if (offset == kKeyRangeUpper) {
            out.set(a, 127);
        } else {
            out.set(a, value);
        }
    } else if (a >= kRhythmSetup && a < kRhythmSetupEnd) {
        switch ((a - kRhythmSetup) % 4) {
        case 0:
            out.set(a, translateRhythmTimbre(value, int((a - kRhythmSetup) / 4)));
            break;
        case 2:
            out.set(a, uint8_t(14 - std::min<uint8_t>(value, 14)));
            break;
        case 3:
            out.set(a, std::min<uint8_t>(value, 1));  // Reverb switch -> output assign MIX (with or without reverb)
            break;
        default:
            out.set(a, value);
            break;
        }
    } else if (a >= kToneTemp && a < kToneTempEnd) {
        const uint32_t part = (a - kToneTemp) / kToneSize;
        translateTone(toneTemp_[part], kToneTemp + part * kToneSize, (a - kToneTemp) % kToneSize, out);
    } else if (a >= kPatchMemory && a < kPatchMemoryEnd) {
        if (!memoryInUnit_) return;  // Kept here: program changes send the parts' timbres
        const uint32_t patch = (a - kPatchMemory) / 8, offset = (a - kPatchMemory) % 8;
        if (offset <= kKeyShift) {
            uint8_t translated[3];
            translatePatch(patchMemory_[patch].data(), translated, -1);
            for (uint32_t i = offset == kKeyShift ? kKeyShift : 0; i < 3; i++) out.set(kPatchMemory + patch * 8 + i, translated[i]);
        } else {
            out.set(a, offset == kReverbSwitch ? std::min<uint8_t>(value, 1) : offset == kDummy ? 0 : value);
        }
    } else if (a >= kToneMemory && a < kToneMemoryEnd && (!memoryInUnit_ || (a - kToneMemory) % 256 < kToneSize)) {
        if (!memoryInUnit_) return;  // Kept here (with the slot's padding): timbre selections send the tone
        const uint32_t tone = (a - kToneMemory) / 256;
        translateTone(toneMemory_[tone], kToneMemory + tone * 256, (a - kToneMemory) % 256, out);
    } else if (a >= kSystem && a < kSystem + kSystemSize) {
        const uint32_t offset = a - kSystem;
        if (offset == kSystemReverbMode) {
            out.set(a, kReverbModes[std::min<uint8_t>(value, 3)]);
        } else if (offset >= kSystemReserves && offset < kSystemReserves + 9 && target_ == Target::D20) {
            // The D-20 takes partial reserves only as a package of all 9, at most 32 partials in total.
            unsigned total = 0;
            for (uint32_t part = 0; part < 9; part++) total += system_[kSystemReserves + part];
            for (uint32_t part = 0; part < 9; part++) {
                const unsigned reserve = system_[kSystemReserves + part];
                out.set(kSystem + kSystemReserves + part, uint8_t(total > 32 ? reserve * 32 / total : reserve));
            }
        } else if (offset >= kSystemChannels && offset < kSystemChannels + 9) {
            if (target_ != Target::D20) out.set(a, value);  // D-20: channels are set on the panel (a dummy here)
        } else if (offset == kSystemMasterVolume) {
            if (!masterVolumeAsVolume_ && target_ != Target::D20) out.set(a, value);  // Else CC 7 (see translateWrite)
        } else {
            out.set(a, value);
        }
    } else {
        out.set(a, value);  // Nothing to translate
    }
}

// Timbre group, number and key shift of a patch (temp or memory): M -> i, and presets A, B and R -> the D-110's a, b
// and r of the same number (preset banks), else the stand-ins; stand-ins with their key shift. A part whose tone the
// unit loads from a cache slot points at the slot.
void Mt32Translator::translatePatch(const uint8_t* patch, uint8_t* out, int part) const {
    const uint8_t group = patch[kGroup] & 3, number = patch[kNumber] & 63;
    int tone = group * 64 + number;
    int keyShift = patch[kKeyShift];
    if (part >= 0 && partSlot_[size_t(part)] >= 0 && cacheActive()) {
        tone = 128 + cacheFirst_ + partSlot_[size_t(part)];
    } else if (group < 2) {
        const PresetChoice& choice = presetChoices_[size_t(group * 64 + number)];
        if (!presetBanks()) tone = choice.tone;
        // An MT-32 timbre sent to the part (or held by the bank) replaces the stand-in, and needs no shift.
        if (!presetIsExact(group * 64 + number)) keyShift += choice.keyShift;
    } else if (group == 3) {
        const int standIn = rhythmStandIn(number);
        if (!presetBanks() || (!rhythmIsExact(number) && standIn == kRhythmOff)) tone = 192 + standIn;
    }
    out[0] = uint8_t(tone / 64);
    out[1] = uint8_t(tone % 64);
    out[2] = uint8_t(std::clamp(keyShift, 0, 48));
}

// Rhythm setup timbre: M1-M64 (0-63) are the unit's tones i11-i88 (or the cache slot holding the MT-32's timbre),
// R1-R64 (64-127) its rhythm tones.
uint8_t Mt32Translator::translateRhythmTimbre(uint8_t value, int key) const {
    if (value < 64) {
        if (key >= 0 && rhythmSlot_[size_t(key)] >= 0 && cacheActive()) return uint8_t(cacheFirst_ + rhythmSlot_[size_t(key)]);
        return value;
    }
    const int timbre = value - 64, standIn = rhythmStandIn(timbre);
    if (presetBanks() && (rhythmIsExact(timbre) || standIn != kRhythmOff)) return value;
    return uint8_t(64 + standIn);
}

void Mt32Translator::translateTone(const Tone& tone, uint32_t base, uint32_t offset, Output& out) const {
    const uint8_t value = tone.data[offset];
    if (offset < kToneCommonSize) {
        out.set(base + offset, value);
        if (tone.known() && (offset == kStructure12 || offset == kStructure34)) {
            // The structure decides which partials play PCM waves, and so which need their waves translated.
            const int first = offset == kStructure12 ? 0 : 2;
            translatePartial(tone, base, first, out);
            translatePartial(tone, base, first + 1, out);
        }
        return;
    }
    const uint32_t partial = (offset - kToneCommonSize) / kPartialSize, parameter = (offset - kToneCommonSize) % kPartialSize;
    const bool dependent = parameter == kPitchCoarse || parameter == kPitchFine || parameter == kWaveform || parameter == kPcmWave;
    if (!dependent) {
        out.set(base + offset, value);
    } else if (tone.known()) {
        translatePartial(tone, base, int(partial), out);
    } else if (parameter == kPcmWave) {
        // Byte by byte: a bank-1 wave, as the waveform byte (which holds the bank) may not come with it.
        const uint8_t waveform = tone.data[offset - (kPcmWave - kWaveform)];
        out.set(base + offset, waveMapping(value + ((waveform & 2) != 0 ? 128 : 0), tone.drumKit).bank1Wave);
    } else if (parameter == kWaveform) {
        out.set(base + offset, value & 1);
    } else {
        out.set(base + offset, value);
    }
}

void Mt32Translator::translatePartial(const Tone& tone, uint32_t base, int partial, Output& out) const {
    const uint32_t start = kToneCommonSize + uint32_t(partial) * kPartialSize;
    const uint8_t* parameters = &tone.data[start];
    const uint8_t structure = tone.data[partial < 2 ? kStructure12 : kStructure34];
    const bool pcm = structure < 13 && (kPartialStruct[structure] & (partial % 2 == 0 ? 2 : 1)) != 0;
    base += start;
    if (!pcm) {
        out.set(base + kPitchCoarse, parameters[kPitchCoarse]);
        out.set(base + kPitchFine, parameters[kPitchFine]);
        out.set(base + kWaveform, parameters[kWaveform]);
        out.set(base + kPcmWave, parameters[kPcmWave]);
        return;
    }
    uint8_t wave = 0, coarse = 0, fine = 0;
    translatePcm(parameters[kPcmWave] + ((parameters[kWaveform] & 2) != 0 ? 128 : 0), parameters[kPitchCoarse], parameters[kPitchFine],
                 wave, coarse, fine, roomyToms_, tone.drumKit);
    out.set(base + kPitchCoarse, coarse);
    out.set(base + kPitchFine, fine);
    out.set(base + kWaveform, uint8_t((parameters[kWaveform] & 1) | (wave >= 128 ? 2 : 0)));
    out.set(base + kPcmWave, uint8_t(wave & 127));
}

void Mt32Translator::selectTimbre(int part) {
    const std::array<uint8_t, 16>& temp = patchTemp_[size_t(part)];
    Tone& tone = toneTemp_[size_t(part)];
    const int group = temp[kGroup] & 3, number = temp[kNumber] & 63;
    toneSent_[size_t(part)] = true;  // The target loads the translated tone itself...
    toneToSend_[size_t(part)] = false;
    partSlot_[size_t(part)] = -1;
    slotFill_[size_t(part)] = false;
    const Mt32Presets::Timbre* preset = nullptr;
    if (presets_ && group < 2) {
        preset = &presets_->melodic[size_t(group * 64 + number)];
    } else if (presets_ && group == 3 && size_t(number) < presets_->rhythm.size()) {
        preset = &presets_->rhythm[size_t(number)];
    }
    if (group == 2) {
        tone = toneMemory_[size_t(number)];  // Memory timbre: known if the MT-32 side wrote it
        if (!memoryInUnit_ && tone.known()) {
            toneSent_[size_t(part)] = false;  // The unit's i tone is its own: send the MT-32's
            toneToSend_[size_t(part)] = true;
        }
    } else if (preset != nullptr) {
        std::memcpy(tone.data.data(), preset->data(), kToneSize);
        tone.written.set();
        // ...unless it plays a stand-in, which the MT-32's own timbre replaces at once where it is chosen (the preset
        // banks hold the MT-32's own already).
        const bool exact = group < 2 ? presetIsExact(group * 64 + number) : rhythmIsExact(number);
        toneSent_[size_t(part)] = exact && presetBanks();
        toneToSend_[size_t(part)] = exact && !presetBanks();
    } else {
        tone.written.reset();  // A preset whose MT-32 data is not known here
    }
    tone.drumKit = group == 3;  // A rhythm timbre keeps the drum kit's waves (see waveMapping())
}

void Mt32Translator::sendTones(uint8_t deviceId, std::vector<uint8_t>& out) {
    for (size_t part = 0; part < 8; part++) {
        if (!toneToSend_[part]) continue;
        toneToSend_[part] = false;
        Output output;
        for (uint32_t offset = 0; offset < kToneSize; offset++) translateTone(toneTemp_[part], kToneTemp + uint32_t(part) * kToneSize, offset, output);
        emit(output, deviceId, out);
        if (slotFill_[part] && partSlot_[part] >= 0) appendToneWrite(int(part), partSlot_[part], deviceId, out);
        slotFill_[part] = false;
        toneSent_[part] = true;
    }
}

void Mt32Translator::programChange(int channel, int program, uint8_t deviceId, std::vector<uint8_t>& sysexOut) {
    for (size_t part = 0; part < 8; part++) {
        if (system_[kSystemChannels + part] != channel) continue;
        std::memcpy(patchTemp_[part].data(), patchMemory_[size_t(program & 127)].data(), 8);
        selectTimbre(int(part));
        resolveSlot(int(part));
        if (!memoryInUnit_) {
            // The part's timbre temp as the patch sets it (tone, key shift, fine tune, bender range, assign mode, reverb).
            Output output;
            writeByte(kPatchTemp + uint32_t(part) * 16 + kGroup, patchTemp_[part][kGroup], output);
            for (uint32_t offset = kKeyShift + 1; offset <= kReverbSwitch; offset++) {
                writeByte(kPatchTemp + uint32_t(part) * 16 + offset, patchTemp_[part][offset], output);
            }
            emit(output, deviceId, sysexOut);
        }
    }
    sendTones(deviceId, sysexOut);
}

void Mt32Translator::emit(const Output& output, uint8_t deviceId, std::vector<uint8_t>& out) {
    std::vector<uint8_t> run;
    size_t i = 0;
    while (i < output.bytes.size()) {
        if (output.bytes[i] < 0) {
            i++;
            continue;
        }
        const size_t first = i;
        run.clear();
        while (i < output.bytes.size() && output.bytes[i] >= 0 && run.size() < 256) run.push_back(uint8_t(output.bytes[i++]));
        appendDataSet(out, deviceId, output.start + uint32_t(first), run.data(), run.size());
    }
}
